import { NextRequest, NextResponse } from 'next/server'
import { otpStore } from '@/lib/otpStore'

const RESEND_API_KEY = 're_9nfY45vC_GjTN9dthEF2s86bh9tG7hmEV'
const FROM = 'NEXUS_TERM <noreply@pangerlkr.link>'
const OTP_TTL_MS = 10 * 60 * 1000 // 10 minutes

export async function POST(req: NextRequest) {
  try {
    const { email } = await req.json()

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return NextResponse.json({ error: 'Invalid email.' }, { status: 400 })
    }

    const otp = String(Math.floor(100000 + Math.random() * 900000))
    const expiresAt = Date.now() + OTP_TTL_MS

    otpStore.set(email.toLowerCase(), { otp, expiresAt, verified: false })

    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: FROM,
        to: [email],
        subject: 'NEXUS_TERM // VERIFICATION_CODE',
        html: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>PANGER_LKR // Contact Verification</title>
</head>
<body style="margin:0;padding:0;background:#050505;font-family:Consolas,Monaco,'Courier New',monospace;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#050505;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="680" cellpadding="0" cellspacing="0" border="0"
          style="background:#020802;border:1px solid #243f00;box-shadow:0 0 40px rgba(187,255,0,0.08);">
          <tr>
            <td style="padding:45px 55px 20px 55px;">
              <div style="margin-bottom:35px;">
                <img src="https://pangerlkr.link/logo.png" alt="PANGER_LKR" width="180"
                  style="display:block;max-width:180px;height:auto;border:0;" />
              </div>
              <div style="color:#728500;font-size:13px;letter-spacing:4px;margin-bottom:18px;">
                PANGER_LKR // CONTACT_SECURITY_GATEWAY
              </div>
              <div style="font-size:48px;font-weight:700;color:#dfff00;line-height:1.2;letter-spacing:2px;text-shadow:0 0 10px rgba(223,255,0,0.15);">
                &gt; USER_E-MAIL_VERIFICATION
              </div>
            </td>
          </tr>
          <tr>
            <td style="padding:0 55px;">
              <div style="height:1px;background:#243f00;"></div>
            </td>
          </tr>
          <tr>
            <td style="padding:45px 55px;">
              <div style="color:#cfe96e;font-size:18px;line-height:1.9;margin-bottom:30px;">
                Greetings,<br><br>
                A message submission request has been initiated through the
                <span style="color:#dfff4d;">PANGER_LKR</span> contact form gateway.<br><br>
                To verify that this request originated from a human operator
                and not an automated spam system, enter the authentication code below.
              </div>
              <table width="100%" cellpadding="0" cellspacing="0" border="0"
                style="background:#010701;border:1px solid #355e00;">
                <tr>
                  <td align="center" style="padding:45px 20px;">
                    <div style="font-size:76px;font-weight:bold;color:#dfff00;letter-spacing:20px;text-shadow:0 0 14px rgba(223,255,0,0.35);">
                      ${otp}
                    </div>
                  </td>
                </tr>
              </table>
              <div style="margin-top:30px;color:#809126;font-size:14px;line-height:2;letter-spacing:2px;">
                REQUEST_STATUS: PENDING_VERIFICATION<br>
                VALIDITY_WINDOW: 10 MINUTES<br>
                ANTI-SPAM PROTOCOL: ACTIVE<br>
                DO NOT SHARE THIS CODE
              </div>
              <div style="margin-top:42px;padding-top:24px;border-top:1px dashed #243f00;color:#6e7d2a;font-size:14px;line-height:1.9;font-style:italic;">
                "Every unchecked gateway invites noise.<br>
                Every verified signal carries intent."
              </div>
            </td>
          </tr>
          <tr>
            <td style="background:#010401;border-top:1px solid #243f00;padding:35px 55px;">
              <div style="color:#5e6921;font-size:13px;line-height:1.8;">
                This verification email was automatically generated by the
                PANGER_LKR website protection infrastructure.<br>
                If you did not attempt to submit a message, you may safely ignore this transmission.
              </div>
              <div style="margin-top:22px;color:#3e4715;font-size:12px;letter-spacing:3px;">
                &copy; 2026 PANGER_LKR // HUMAN_VERIFICATION_NODE
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`,
      }),
    })

    if (!res.ok) {
      const err = await res.text()
      console.error('Resend error:', err)
      return NextResponse.json({ error: 'Failed to send email.' }, { status: 500 })
    }

    return NextResponse.json({ success: true })
  } catch (e) {
    console.error(e)
    return NextResponse.json({ error: 'Internal error.' }, { status: 500 })
  }
}
